import {
  AlignJustify,
  ArrowUpToLine,
  BrickWall,
  CloudRain,
  DoorClosed,
  Droplet,
  Home,
  Layers,
  LayoutGrid,
  Lightbulb,
  Plug,
  Server,
  Shield,
  ToggleRight,
  Truck,
  Waves,
} from "lucide-react"

import type { ChecklistConfig } from "@/components/es-dashboard/shared-checklist-form"

export const FRM_TSM_002_CONFIG: ChecklistConfig = {
  formCode: "FRM_TSM_002",
  formName: "Form Checklist Warehouse",
  items: [
    { id: "1", label: "Saklar", icon: ToggleRight },
    { id: "2", label: "Lampu", icon: Lightbulb },
    { id: "3", label: "Panel Listrik", icon: Server },
    { id: "4", label: "Stop kontak", icon: Plug },
    { id: "5", label: "Dinding / partisi", icon: BrickWall },
    { id: "6", label: "Lantai", icon: LayoutGrid },
    { id: "7", label: "Pintu", icon: DoorClosed },
    { id: "8", label: "Rolling door", icon: AlignJustify },
    { id: "9", label: "Plafon", icon: ArrowUpToLine },
    { id: "10", label: "Bantalan truck", icon: Truck },
    { id: "11", label: "Atap Zincalume / atap skylight", icon: Home },
    { id: "12", label: "Talang", icon: CloudRain },
    { id: "13", label: "Kaki rak / protector", icon: Shield },
    { id: "14", label: "Mezanine", icon: Layers },
    { id: "15", label: "Keran", icon: Droplet },
    { id: "16", label: "Saluran air kotor (Drainase)", icon: Waves },
  ],
  conditionOptions: [
    "ADJUST_OR_ADD",
    "CLEAN",
    "REPAIR",
    "URGENT",
    "BAIK",
    "RUSAK",
    "TIDAK_ADA",
  ],
  conditionLabels: {
    ADJUST_OR_ADD: "Adjust/Add (A)",
    CLEAN: "Clean (C)",
    REPAIR: "Repair (R)",
    URGENT: "Urgent (U)",
    BAIK: "Baik (V)",
    RUSAK: "Rusak (X)",
    TIDAK_ADA: "Tidak Ada (T)",
  },
  conditionRequiresPhoto: (condition) => condition === "RUSAK",
}
